algoritmo "Estrutura Idade"

var
nome:caracter
idade:inteiro

inicio
escreval("Digite seum nome:")
leia(nome)
escreval("Digite sua idade:")
leia(idade)

se idade >=18 entao
se idade>=65 entao 
escreval(nome," você e maior de idade, por ainda isso é idoso")
senao
escreval(nome," você e maior de idade e nao é um idoso")
fimse
senao
escreval(nome," voce ainda nao é maior de idade")
fimse

fimalgoritmo